[project]
name = "heavy_deps"
version = "0.1.0"
dependencies = ["numpy", "pandas", "matplotlib"]

[tool.pycrucible]
entry = "main.py"

[tool.pycrucible.options]
debug = false
extract_to_temp = false
delete_after_run = false