[project]
name = "fastapi_app"
version = "0.1.0"
dependencies = ["fastapi", "uvicorn"]

[tool.pycrucible]
entry = "app.py"

[tool.pycrucible.options]
debug = false
extract_to_temp = false
delete_after_run = false